### ISSUE TITLE
migrate ocp4

### ISSUE THREAD

**Issue by DanielFroehlich** [stormshift/automation#58]
ODF VMes from storm3:
compute0: pci_0000_81_00_0 on storm3
compute1: pci_0000_83_00_0 on storm3
compute2:  pci_0000_84_00_0 on storm3

### ToDo's 

- [x] ⚪ Cleanup the cluster - remove old not used workload (boby car for example?)
   - Removed old open-cluster-managedment
   - Several orphan workloads from Red Haters not at Red Hat anymore and more
   - Costmanagment operator deinstalled
   - Deleted orphan sunset/sunsetdb in openshift-operators
- [X] 🟢 Add NetApp Trident CSI NFS Storage driver for new store requests
- [ ] 🛠️  Migrate / Remove all ODF PVC to NetApp Storage
   - [X] 🟢 Cluster Monitoring
   - [x] 🟢 Internal Registry
   - [x] 🟢 User / Workload PVC - E-Mail to all Users - WiP: https://github.com/stormshift/automation/issues/58#issuecomment-2560254407
   - [X] 🟢 Remove ODF
- [x] 🟢 Remove managed-nfs-prov. NFS Server provided from support node
- [x] 🟢 Prepare a ocp4 network in COE LAb 172.16.10.0/24 (dgw: 172.16.10.1, dns: 172.16.10.5), VLAN ID: 1004 VLAN-NAme: stormshift-ocp4 
  - [x] 🟢  Prepare router VM - not needed already done by bastion
- [x] 🟢 Services at ocp4support vm: dhcpd, dns server, router 
- [x] 🟢 Create a VLAN Based network
- [x] 🟢 Shutdown all VM's change network into the vlan based network
- [x] 🟢 Add NetApp into the VLAN
- [x] 🟢  Migrate storage (PV/PVC) to NetApp (https://access.redhat.com/solutions/7089972)
- [X] 🟢   Run MTV to migration VM's from RHV to OpenShift-Virt into the same VLAN. Based case without any cluster downtime.
    - ⚠️ Difficult: During the migration, the chipset will change from `I440FX` to `q35`. The  result is the interface name changed from `ens2` to `enp1s0`. And network configuration gets lost because it's still at to the old interface. (https://issues.redhat.com/browse/MTV-1847)
- [X] 🟢 Rollout `/etc/udev/rules.d/70-persistent-net.rules` to persiste device after chipset change
   - [x] ocp4bastion
   - [x] ocp4support
   - [x] ocp4compute-0
   - [x] ocp4compute-1
   - [x] ocp4compute-2
   - [x] ocp4control-0
   - [x] ocp4control-1
   - [x] ocp4control-2 
- 🔴 AFTER ALL - Migrate VM's from RHV to OpenShift-Virt

/cc @Javatar81

**Comment by rbo** [comment]
Is there any hard requirement for ODF on that cluster?

**Comment by rbo** [comment]
ToDo's 

- [ ] Cleanup the cluster - remove old not used workload (boby car for example?)
- [ ] Add NetApp Trident CSI NFS Storage driver for new store requests
- [ ] Migrate / Remove all ODF PVC to NetApp Storage
- [ ] Remove managed-nfs-prov. NFS Server provided from support node
- [ ] Prepare a ocp4 network in COE LAb 172.16.10.0/24 (dgw: 172.16.10.1, dns: 172.16.10.5), VLAN ID: 1004 VLAN-NAme: stormshift-ocp4 
  - [ ] Prepare router VM

Services at ocp4support vm:
  * dhcpd
  * dns forwarder 

Idea: 
 - Create a VLAN Based network
 - Shutdown all VM's change network into the vlan based network
 - Add NetApp into the VLAN
 - Migrate storage (PV/PVC) to NetApp
 - Run MTV to migration VM's from RHV to OpenShift-Virt into the same VLAN. Based case without any cluster downtime.

/cc @Javatar81

**Comment by rbo** [comment]
### VLAN configuration
* [Documented](https://docs.google.com/spreadsheets/d/1iwXilV1V84IQN7mKOIHq28-9P5bWabN019TJPaJ_3Es/edit?gid=116822073#gid=116822073)

<details>
<summary>Switch configuration arista-sfp</summary>

```
arista-sfp>enable
arista-sfp#config
arista-sfp(config)#vlan 1004
arista-sfp(config-vlan-1004)#name stormshift-ocp4
arista-sfp(config-vlan-1004)#interface Et1-36
arista-sfp(config-if-Et1-4,6/1-36)#switchport trunk allowed vlan add 1004
arista-sfp(config-if-Et1-4,6/1-36)#interface Po11
arista-sfp(config-if-Po11)#switchport trunk allowed vlan add 1004
arista-sfp(config-if-Po11)#write
Copy completed successfully.
arista-sfp(config-if-Po11)#copy running-config startup-config
Copy completed successfully.
arista-sfp(config-if-Po11)#
```

</details>

<details>
<summary>Switch configuration arista-rj45</summary>

```
arista-rj45>enable
arista-rj45#config
arista-rj45(config)#vlan 1004
arista-rj45(config-vlan-1004)#name stormshift-ocp4
arista-rj45(config-vlan-1004)#interface Et1-Et48
arista-rj45(config-if-Et1-48)#switchport trunk allowed vlan add 1004
arista-rj45(config-if-Et1-48)#interface Po11
arista-rj45(config-if-Po11)#switchport trunk allowed vlan add 1004
arista-rj45(config-if-Po11)#write
Copy completed successfully.
arista-rj45(config-if-Po11)#copy running-config startup-config
Copy completed successfully.
arista-rj45(config-if-Po11)#
```

</details>

**Comment by rbo** [comment]
Created a test rhel 9.1 VM at RHEV and OCP-V VM's can comunicate and have access to NetApp. 

Tested MTV of test vm: Moved from RHV to OCP-V - problem: network interface name changed and lost of static IP config. Not good...  FI: ocp4 use dhcp.... not static IP.

**Comment by rbo** [comment]
https://issues.redhat.com/browse/MTV-1847

**Comment by rbo** [comment]
Tried to migrate ocp4support,
```
admission webhook "virtualmachine-validator.kubevirt.io" denied the request: failure checking preference requirements: insufficient Memory resources of 1Gi provided by VirtualMachine, preference requires 1536Mi
```
Memory Size: 1024 MB 

To test the migration changed the memory size to 2048.

**Comment by rbo** [comment]
### Moved VMs into VLAN 1004 ✅ 
* Shutdown cluster via https://examples.openshift.pub/cluster-lifecycle/shutdown/
* Changed network of all VM's
* Start up cluster again

**Comment by rbo** [comment]
### managed-nfs-prov removed ✅

**Comment by rbo** [comment]
### NetApp Trident configured ✅ 


```
Warning  Failed  81s (x17 over 6m58s)  trident-crd-controller  Failed to create backend: problem initializing storage driver 'ontap-san-economy': could not configure storage pools: could not get storage pools from array: SVM stormshift-ocp4 has no assigned aggregates
```

```
fas2552::> vserver show -fields aggr-list
vserver aggr-list
------- --------------
disco   fas2552_02_SAS
fas2552 -
fas2552-01
        -
fas2552-02
        -
main    fas2552_02_SAS
manual  -
stormshift-ocp4
        -
svm_trident
        fas2552_02_SAS
8 entries were displayed.

fas2552::> vserver add-aggregates -vserver stormshift-ocp4 -aggregates  fas2552_02_SAS

fas2552::> vserver show -fields aggr-list
vserver aggr-list
------- --------------
disco   fas2552_02_SAS
fas2552 -
fas2552-01
        -
fas2552-02
        -
main    fas2552_02_SAS
manual  -
stormshift-ocp4
        fas2552_02_SAS
svm_trident
        fas2552_02_SAS
8 entries were displayed.

fas2552::>
fas2552::>

```

**Comment by rbo** [comment]
We have to fix the multipath config:
```
sh-5.1# multipath -ll
0QEMU_QEMU_HARDDISK_1cb43761-2193-43d9-b6b9-5b6f164b5435 dm-1 QEMU,QEMU HARDDISK
size=10G features='0' hwhandler='0' wp=rw
`-+- policy='service-time 0' prio=1 status=active
  `- 0:0:0:0 sda     8:0   active ready running
nvme.8086-43564654353436313030333932503045474e-494e54454c205353445045444d443032305434-00000001 dm-0 NVME,INTEL SSDPEDMD020T4
size=1.8T features='0' hwhandler='0' wp=rw
`-+- policy='service-time 0' prio=1 status=active
  `- 0:0:1:1 nvme0n1 259:0 active ready running

```

Configuration right now:
```
defaults {
   user_friendly_names no
   find_multipaths no
   enable_foreign "^$"
}

blacklist_exceptions {
    property "(SCSI_IDENT_|ID_WWN)"
}

blacklist {
    devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
    devnode "^(td|ha)d[a-z]"
    device {
        vendor  "HP"
    }
    device {
        vendor  "Intel"
    }
    device {
        vendor  "HGST"
    }
}
```

**Comment by rbo** [comment]
#### Storage migration with MTC
Tried:
```
apiVersion: migration.openshift.io/v1alpha1
kind: MigPlan
metadata:
  annotations:
    migration.openshift.io/selected-migplan-type: scc
  name: image-registry
  namespace: openshift-migration
spec:
  destMigClusterRef:
    name: host
    namespace: openshift-migration
  liveMigrate: false
  namespaces:
    - openshift-image-registry
  persistentVolumes:
    - capacity: 100Gi
      name: pvc-8059a107-3874-4ac3-b4a2-a747539fb712
      proposedCapacity: 100Gi
      pvc:
        accessModes:
          - ReadWriteMany
        hasReference: true
        name: 'registry-storage-netapp-nas'
        namespace: openshift-image-registry
        volumeMode: Filesystem
      selection:
        action: copy
        copyMethod: filesystem
        storageClass: coe-netapp-nas
        verify: true
      storageClass: ocs-storagecluster-cephfs
      supported:
        actions:
          - skip
          - copy
        copyMethods:
          - filesystem
          - block
          - snapshot
  srcMigClusterRef:
    name: host
    namespace: openshift-migration
```

Works not too bad...
